apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: it-patch-management-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: it-patch-management-deployment-v1
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50

#increase the load - 
#kubectl run -i --tty load-generator --rm --image=busybox:1.28 --restart=Never -- /bin/sh -c "while sleep 0.01; do wget -q -O- http://it-patch-management:8080; done"